### ISSUE TITLE
Include Resource files option failing

### ISSUE THREAD

**Issue by DevSlick** [tobania/VSTS.Extension.SqlReportingServices#12]
When choosing the **Include Resource files** option and setting it up as the tooltip describes, the following error always occurs:

2017-06-07T17:23:36.1946565Z ##[error]System.Management.Automation.ParameterBindingException: A positional parameter cannot be found that accepts argument '+'.

![capture](https://user-images.githubusercontent.com/29259537/26892098-082e75a4-4b6c-11e7-832c-d266ea99a6f7.PNG)

**Comment by DevSlick** [comment]
I believe line 233 should be:

$props = New-Object "System.Collections.Generic.List[$type.Property]";

**Comment by muziekklas** [comment]
We take a look tomorrow. Might be indeed line 233.

Op 7 jun. 2017 8:10 p.m. schreef "Nick" <notifications@github.com>:

I believe line 233 should be:

$props = New-Object "System.Collections.Generic.List[$type.Property]";

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tobania/VSTS.Extension.SqlReportingServices/issues/12#issuecomment-306878885>,
or mute the thread

**Comment by muziekklas** [comment]
@DevSlick  Can you verify that the last change did resolve this?  I have changed all the new-objects where i use the $type variable as you stated (which was correct by the way) :)

**Comment by DevSlick** [comment]
Yes. I can verify that the fix does work.

**Comment by muziekklas** [comment]
Lovely :) thanks!
